### ISSUE TITLE
💡 RFC: MVP Goal

### ISSUE THREAD

**Issue by isaiahdahl** [bettermusic/studio#60]
### High level objective
Replace PraiseCharts chordpro editor. 

#### Tasks
 
- [ ] more complete syntax highlighting 
- [ ] choose from multiple chordpro examples
- [ ] #61
- [ ] autocomplete of chords
- [ ] play mode / edit mode
- [ ] immutable metadata
